FROM ghcr.io/datadog/images-rb/engines/ruby:2.6-gnu

RUN apt-get install -y \
    binutils \
    file \
    make \
    libc6-dev \
    libmariadb-dev \
    libmariadb-dev-compat \
    libpq-dev \
    libsqlite3-dev \
    gcc \
    g++ \
    --no-install-recommends
