FROM ghcr.io/datadog/images-rb/engines/ruby:2.5-gnu

RUN apt-get install -y \
    binutils \
    file \
    make \
    libc6-dev \
    libmariadb-dev \
    libmariadb-dev-compat \
    libpq-dev \
    libsqlite3-dev \
    clang \
    --no-install-recommends

RUN printf '%s\n' '#!/bin/sh' 'exec clang -fdeclspec "$@"' > /usr/local/bin/gcc \
    && chmod +x /usr/local/bin/gcc
