FROM ghcr.io/datadog/images-rb/engines/ruby:2.5-centos

RUN yum install -y epel-release && yum install -y gcc clang make binutils file patch sqlite-devel && ln -s "$(command -v clang)" /usr/local/bin/gcc
