FROM ghcr.io/datadog/images-rb/engines/ruby:3.2-musl

RUN apk add \
    binutils \
    file \
    fortify-headers \
    g++ \
    gcc \
    make \
    mariadb-connector-c-dev \
    musl-dev \
    postgresql-dev \
    sqlite-dev
