FROM ghcr.io/datadog/images-rb/engines/ruby:3.0-musl

RUN apk add \
    binutils \
    clang \
    file \
    fortify-headers \
    gcc \
    make \
    mariadb-connector-c-dev \
    musl-dev \
    postgresql-dev \
    sqlite-dev \
    && ln -s "$(command -v clang)" /usr/local/bin/gcc
