name: Main

on:
  workflow_dispatch:
    inputs:
      push:
        description: Push release images
        required: true
        type: boolean
        default: true
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ inputs.push && 'publish' || github.run_id }}
  cancel-in-progress: false

jobs:
  services:
    name: Services
    uses: ./.github/workflows/services.yml
    with:
      push: ${{ github.event_name == 'workflow_dispatch' && inputs.push && github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write

  ruby:
    name: Ruby
    uses: ./.github/workflows/ruby.yml
    with:
      push: ${{ github.event_name == 'workflow_dispatch' && inputs.push && github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write

  nix:
    name: Nix
    uses: ./.github/workflows/nix.yml
    permissions:
      contents: read
      id-token: write

  complete:
    name: Main (complete)
    needs:
      - services
      - ruby
      - nix
    runs-on: ubuntu-24.04
    steps:
      - name: Done
        run: |
          echo 'DONE!'
