name: Main

on:
  push:
    branches:
      - "**"

jobs:
  build-services:
    name: Build Services
    uses: ./.github/workflows/build-services.yml
    permissions:
      packages: write

  build-ruby:
    name: Build Ruby
    uses: ./.github/workflows/build-ruby.yml
    permissions:
      packages: write

  nix:
    name: Nix
    uses: ./.github/workflows/nix.yml
    permissions:
      contents: read
      id-token: write

  complete:
    name: Main (complete)
    needs:
      - build-services
      - build-ruby
      - nix
    runs-on: ubuntu-24.04
    steps:
      - name: Done
        run: |
          echo 'DONE!'
